### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Socks4linqq** [3arthqu4ke/HeadlessForge#1]
Starting HeadlessForge with Arguments: [C:\Users\administrator\AppData\Roaming\.minecraft\mods]
Starting Launchwrapper...
Exception in thread "main" java.lang.NoClassDefFoundError: net/minecraft/launchwrapper/Launch
        at me.earth.headlessforge.launch.Main$Companion.main(Main.kt:113)
        at me.earth.headlessforge.launch.Main.main(Main.kt)
Caused by: java.lang.ClassNotFoundException: net.minecraft.launchwrapper.Launch
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 2 more

**Comment by Socks4linqq** [comment]
nvm
