### ISSUE TITLE
im now getting this error

### ISSUE THREAD

**Issue by Socks4linqq** [3arthqu4ke/HeadlessForge#2]
[18:13:14] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at me.earth.headlessforge.launch.Main$Companion.main(Main.kt:113) [headlessforge.jar:?]
        at me.earth.headlessforge.launch.Main.main(Main.kt) [headlessforge.jar:?]
Caused by: java.lang.UnsatisfiedLinkError: no lwjgl64 in java.library.path
        at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:1.8.0_281]
        at java.lang.Runtime.loadLibrary0(Unknown Source) ~[?:1.8.0_281]
        at java.lang.System.loadLibrary(Unknown Source) ~[?:1.8.0_281]
        at org.lwjgl.Sys$1.run(Sys.java:72) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_281]
        at org.lwjgl.Sys.doLoadLibrary(Sys.java:66) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
        at org.lwjgl.Sys.loadLibrary(Sys.java:87) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
        at org.lwjgl.Sys.<clinit>(Sys.java:117) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
        at net.minecraft.client.Minecraft.func_71386_F(Minecraft.java:2984) ~[bib.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:38) ~[Main.class:?]
        ... 8 more
Exception in thread "main" [18:13:14] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[18:13:14] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:  at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[18:13:14] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:  at java.lang.SecurityManager.checkExit(Unknown Source)
[18:13:14] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:  at java.lang.Runtime.exit(Unknown Source)
[18:13:14] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:  at java.lang.System.exit(Unknown Source)
[18:13:14] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:  at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[18:13:14] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:  at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[18:13:14] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:  at me.earth.headlessforge.launch.Main$Companion.main(Main.kt:113)
[18:13:14] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:  at me.earth.headlessforge.launch.Main.main(Main.kt)

**Comment by 3arthqu4ke** [comment]
What exactly did you type in on the console?
Try just "java -jar <headlessforge.jar name> <Path to .minecraft folder>".

**Comment by Socks4linqq** [comment]
i did exactly that but it didnt work

**Comment by 3arthqu4ke** [comment]
Ok I didn't read the Exception properly.
This really shouldn't happen. Do you have Forge 1.12.2 - 14.23.5.2854 installed?

**Comment by oHare2** [comment]
Looks like an invalid forge version I suggest installing the recommended forge version.

**Comment by Socks4linqq** [comment]
i downloaded that same version and i get the same error. Is it something to do with the graphics card on the vps cause when i try to launch minecraft normally in a vps it crashes and says i have a bad graphics driver

**Comment by 3arthqu4ke** [comment]
No drivers have nothing to do with this. I have no clue how you managed to get that error, I can't recreate it and it should work see [here](https://github.com/3arthqu4ke/HeadlessForge/blob/085407d956e2a2e8b4b118de45cbf61217178bce/src/main/java/me/earth/headlessforge/mixin/MixinMinecraft.java#L229). Do you use any other mods and what happens if you type java -version on the console?

**Comment by Socks4linqq** [comment]
im not using any mods. This is what i get when i type java -version

java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) Client VM (build 25.211-b12, mixed mode, sharing)

**Comment by Socks4linqq** [comment]
what should i do men

**Comment by 3arthqu4ke** [comment]
Only thing you could try is going through the bin folder and find a folder that contains a lwjgl64.dll file. Then copy the path to that folder and start like this: **java -jar headlessforge-1.0.jar <Path to .minecraft> <path to folder with lwjgl64.dll>**. I can't reproduce your error and it shouldn't happen anyways. Make sure the headlessforge.jar is in your mods folder and you use java -jar in there

**Comment by 3arthqu4ke** [comment]
Did you build the jar yourself or are you using the one from the releases?

**Comment by Socks4linqq** [comment]
i built it myself

**Comment by Socks4linqq** [comment]
org.lwjgl.LWJGLException: Pixel format not accelerated
        at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
        at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
        at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
        at org.lwjgl.opengl.Display.createWindow(Display.java:306) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
        at org.lwjgl.opengl.Display.create(Display.java:848) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
        at org.lwjgl.opengl.Display.create(Display.java:757) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
        at net.minecraft.client.Minecraft.func_175609_am(Minecraft.java:625) [bib.class:?]
        at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:458) [bib.class:?]
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) [bib.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at me.earth.headlessforge.launch.Main$Companion.main(Main.kt:113) [headlessforge-1.0.jar:?]
        at me.earth.headlessforge.launch.Main.main(Main.kt) [headlessforge-1.0.jar:?]
[14:38:43] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----
// My bad.

Time: 4/6/21 2:38 PM
Description: Initializing game

org.lwjgl.LWJGLException: Pixel format not accelerated
        at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
        at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
        at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247)
        at org.lwjgl.opengl.Display.createWindow(Display.java:306)
        at org.lwjgl.opengl.Display.create(Display.java:848)
        at org.lwjgl.opengl.Display.create(Display.java:757)
        at org.lwjgl.opengl.Display.create(Display.java:739)
        at net.minecraft.client.Minecraft.func_175609_am(Minecraft.java:645)
        at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:458)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
        at net.minecraft.client.main.Main.main(SourceFile:123)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        at me.earth.headlessforge.launch.Main$Companion.main(Main.kt:113)
        at me.earth.headlessforge.launch.Main.main(Main.kt)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
        at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
        at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
        at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247)
        at org.lwjgl.opengl.Display.createWindow(Display.java:306)
        at org.lwjgl.opengl.Display.create(Display.java:848)
        at org.lwjgl.opengl.Display.create(Display.java:757)
        at org.lwjgl.opengl.Display.create(Display.java:739)
        at net.minecraft.client.Minecraft.func_175609_am(Minecraft.java:645)
        at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:458)

-- Initialization --
Details:
Stacktrace:
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
        at net.minecraft.client.main.Main.main(SourceFile:123)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        at me.earth.headlessforge.launch.Main$Companion.main(Main.kt:113)
        at me.earth.headlessforge.launch.Main.main(Main.kt)

-- System Details --
Details:
        Minecraft Version: 1.12.2
        Operating System: Windows Server 2019 (amd64) version 10.0
        Java Version: 1.8.0_281, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 371826008 bytes (354 MB) / 652214272 bytes (622 MB) up to 1670381568 bytes (1593 MB)
        JVM Flags: 0 total;
        IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
        FML:
        Loaded coremods (and transformers):
        Launched Version: 1.12.2-forge-14.23.5.2854
        LWJGL: 2.9.4
        OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
        GL Caps:
        Using VBOs: Yes
        Is Modded: Definitely; Client brand changed to 'fml,forge'
        Type: Client (map_client.txt)
        Resource Packs:
        Current Language: ~~ERROR~~ NullPointerException: null
        Profiler Position: N/A (disabled)
        CPU: <unknown>

**Comment by 3arthqu4ke** [comment]
Yeah that means the mod isn't being applied which shouldn't happen. Is you mods folder in the .minecraft folder? Or in a sub folder in .minecraft?

**Comment by 3arthqu4ke** [comment]
Ah you built it yourself. Go check that [the field "Hooks"](https://github.com/3arthqu4ke/HeadlessForge/blob/085407d956e2a2e8b4b118de45cbf61217178bce/src/main/kotlin/me/earth/headlessforge/inject/Hooks.kt) is set to true.

**Comment by 3arthqu4ke** [comment]
I mean this one:

**private const val HOOK = true**

**Comment by Socks4linqq** [comment]
it is already set to true

**Comment by Socks4linqq** [comment]
> Yeah that means the mod isn't being applied which shouldn't happen. Is you mods folder in the .minecraft folder? Or in a sub folder in .minecraft?

its in the .minecraft folder

**Comment by Socks4linqq** [comment]
i want tto use this for ping bypass. I can try to use tlauncher instead because minecraft is working normally on there now for some reason. Does ping bypass work on tlauncher?

**Comment by 3arthqu4ke** [comment]
Last thing you could try is using the [release](https://github.com/3arthqu4ke/HeadlessForge/releases/tag/1.0). I don't know anything else that could cause that.

**Comment by 3arthqu4ke** [comment]
I don't know about tlauncher.

**Comment by 3arthqu4ke** [comment]
The server.json should be already there if you started the game once. You can check syntax in there and then yes, replace ip and port with internal ip and the forwared port of the vps.

**Comment by Socks4linqq** [comment]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from PingBypass (pingbypass)
Caused by: java.net.BindException: Cannot assign requested address: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Unknown Source)
	at sun.nio.ch.Net.bind(Unknown Source)
	at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:554)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1258)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:980)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:250)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:365)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Unknown Source)

**Comment by Socks4linqq** [comment]
i get this error everytime

**Comment by 3arthqu4ke** [comment]
Well what does your server.json look like?

**Comment by Socks4linqq** [comment]
ServerIP: 13.82.100.225:3389

i just searched up whats my ip on google and i used the forwarded port i used to connect to the vps

**Comment by 3arthqu4ke** [comment]
It should not look like that.

This is how you should make it look:

{
  "Bind": "NONE",
  "IServerIP": "13.82.100.225",
  "Port": 3389
  "NoRender": false,
  "Hidden": false,
  "Enabled": true,
  "Name": "Server"
}

**Comment by 3arthqu4ke** [comment]
Sec Im stupid

**Comment by 3arthqu4ke** [comment]
No thats exactly what it should look like.

**Comment by Socks4linqq** [comment]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from PingBypass (pingbypass)
Caused by: java.net.BindException: Cannot assign requested address: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:437)
	at sun.nio.ch.Net.bind(Net.java:429)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:554)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1258)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:980)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:250)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:365)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Socks4linqq** [comment]
im getting this now

**Comment by 3arthqu4ke** [comment]
Ensure that the port isn't in use.

**Comment by Socks4linqq** [comment]
ive been trying that but im still getting the error

**Comment by Socks4linqq** [comment]
is there any way i could find a port that isnt in use
