### ISSUE TITLE
Crash on startup (java.lang.reflect.InvocationTargetException: null)

### ISSUE THREAD

**Issue by GodSaveTheDoge** [3arthqu4ke/HeadlessForge#3]
When trying to run it (`java8 -jar headlessforge-1.1.jar ~/.minecraft`), it crashes.

<details>
<summary>Output</summary>
Starting HeadlessForge with Arguments: [/home/doggo/.minecraft]
Starting Launchwrapper...
[12:17:23] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[12:17:23] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[12:17:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[12:17:23] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2854 for Minecraft 1.12.2 loading
[12:17:23] [main/INFO] [FML]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_265, running on Linux:amd64:5.4.0-72-generic, installed at /usr/lib/jvm/java-8-openjdk-amd64/jre
[12:17:24] [main/INFO] [FML]: Searching /home/doggo/.minecraft/mods for mods
[12:17:24] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[12:17:24] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[12:17:24] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[12:17:24] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[12:17:24] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:17:27] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[12:17:27] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[12:17:27] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:17:27] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[12:17:27] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[12:17:27] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[12:17:27] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[12:17:28] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at me.earth.headlessforge.launch.Main$Companion.main(Main.kt:116) [headlessforge-1.1.jar:?]
        at me.earth.headlessforge.launch.Main.main(Main.kt) [headlessforge-1.1.jar:?]
Caused by: java.lang.UnsatisfiedLinkError: no lwjgl64 in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860) ~[?:1.8.0_265]
        at java.lang.Runtime.loadLibrary0(Runtime.java:871) ~[?:1.8.0_265]
        at java.lang.System.loadLibrary(System.java:1124) ~[?:1.8.0_265]
        at org.lwjgl.Sys$1.run(Sys.java:72) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_265]
        at org.lwjgl.Sys.doLoadLibrary(Sys.java:66) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
        at org.lwjgl.Sys.loadLibrary(Sys.java:87) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
        at org.lwjgl.Sys.<clinit>(Sys.java:117) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
        at net.minecraft.client.Minecraft.func_71386_F(Minecraft.java:2984) ~[bib.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:38) ~[Main.class:?]
        ... 8 more
Exception in thread "main" [12:17:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[12:17:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:        at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[12:17:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:        at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[12:17:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:        at java.lang.Runtime.exit(Runtime.java:107)
[12:17:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:        at java.lang.System.exit(System.java:973)
[12:17:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:        at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[12:17:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[12:17:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:        at me.earth.headlessforge.launch.Main$Companion.main(Main.kt:116)
[12:17:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:        at me.earth.headlessforge.launch.Main.main(Main.kt)
</details>

<details>
<summary>Versions</summary>
<ul>
<li><b>Os</b>: Ubuntu 20.04</li>
<li><b>Java</b>: 
<code>
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0ubuntu2~20.04-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)
</code>
</li>
<li><b>HeadlessForge</b>: 1.1 (release, not built)</li>
<li><b>Forge</b>: 14.23.5.2854 (1.12)</li>
</ul>
</details>

**Comment by GodSaveTheDoge** [comment]
I have considered https://github.com/3arthqu4ke/HeadlessForge/issues/2 but specifying the lwjgl folder doesn't seem to help.

(Downloaded from [here](https://github.com/LWJGL/lwjgl3/releases/tag/3.2.3) and i passed lwjgl-3.2.3/lwjgl)

**Comment by GodSaveTheDoge** [comment]
looks like I'm too dumb to know how to download lwjgl

**Comment by GodSaveTheDoge** [comment]
Still have no idea where to get lwjgl64.so but in doubt i stole lunar client's one (in /home/doggo/.lunarclient/offline/files/1.12/natives/).

**Comment by GodSaveTheDoge** [comment]
apparently you don't need to specify the lwjgl dir, you simply need to put headlessforge's jar in the mods folder 🤦🏼
