### ISSUE TITLE
help

### ISSUE THREAD

**Issue by proxyo1** [3arthqu4ke/HeadlessForge#4]
proxyyy@bruh:~$ sudo java -jar /home/proxyyy/.local/share/multimc/instances/proxy/.minecraft/mods/headlessforge-1.1.jar
No .minecraft path given, assuming we are .minecraft/mods...
Starting HeadlessForge with Arguments: []
Starting Launchwrapper...
Exception in thread "main" java.lang.NoClassDefFoundError: net/minecraft/launchwrapper/Launch
        at me.earth.headlessforge.launch.Main$Companion.main(Main.kt:116)
        at me.earth.headlessforge.launch.Main.main(Main.kt)
Caused by: java.lang.ClassNotFoundException: net.minecraft.launchwrapper.Launch
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 2 more

**Comment by proxyo1** [comment]
on ssh ubuntu 
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~18.04-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)

**Comment by 3arthqu4ke** [comment]
I can't really tell whats wrong from that log. Here's some ideas:
- Make sure you have 1.12.2-forge-14.23.5.2854 installed (and only that exact version).
- cd into the /mods directory so you only have to do java -jar headlessforge-1.1.jar.
- Make sure that your .minecraft is set up properly. There should be a "versions" and a "libraries" folder.

**Comment by proxyo1** [comment]
im using multimc

**Comment by 3arthqu4ke** [comment]
I doubt that will work then.
