### ISSUE TITLE
crashing on startup

### ISSUE THREAD

**Issue by cheroso1337** [3arthqu4ke/HeadlessForge#5]
```
root@cherfofin:~/.minecraft/mods# java -jar headlessforge-1.1.jar 
No .minecraft path given, assuming we are .minecraft/mods...
Starting HeadlessForge with Arguments: []
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by me.earth.headlessforge.launch.Main$Companion (file:/root/.minecraft/mods/head
lessforge-1.1.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of me.earth.headlessforge.launch.Main$Companion
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.IllegalArgumentException: object is not an instance of declaring class
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at me.earth.headlessforge.launch.Main$Companion.main(Main.kt:81)
        at me.earth.headlessforge.launch.Main.main(Main.kt)
root@cherfofin:~/.minecraft/mods# 
```

Mods : InGameAccountSwitcher-Forge-1.12.2-7.0.7.jar  headlessforge-1.1.jar 
OptiFine_1.12.2_HD_U_G5.jar                   pingbypass-1.0.0-release.jar

😭

**Comment by 3arthqu4ke** [comment]
You need Java 8.

**Comment by cheroso1337** [comment]
```
root@pingbypass:~/.minecraft/mods# ls
InGameAccountSwitcher-Forge-1.12.2-7.0.7_1.jar  OptiFine_1.12.2_HD_U_G5.jar  headlessforge-1.1.jar  logs  pingbypass-1.0.0-release.jar
root@pingbypass:~/.minecraft/mods# java -version
java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)
root@pingbypass:~/.minecraft/mods# java -jar  headlessforge-1.1.jar 
No .minecraft path given, assuming we are .minecraft/mods...
Starting HeadlessForge with Arguments: []
Starting Launchwrapper...
[11:46:55] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[11:46:55] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraftforge.fml.common.launcher.FMLTweaker
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_291]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_291]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355) ~[?:1.8.0_291]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_291]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_291]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_291]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_291]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_291]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at me.earth.headlessforge.launch.Main$Companion.main(Main.kt:116) [headlessforge-1.1.jar:?]
        at me.earth.headlessforge.launch.Main.main(Main.kt) [headlessforge-1.1.jar:?]
root@pingbypass:~/.minecraft/mods# 
```

**Comment by cheroso1337** [comment]
now i get this

```
root@pingbypass:~/.minecraft/mods# java -jar  headlessforge-1.1.jar 
No .minecraft path given, assuming we are .minecraft/mods...
Starting HeadlessForge with Arguments: []
Starting Launchwrapper...
[11:32:19] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[11:32:19] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraftforge.fml.common.launcher.FMLTweaker
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_291]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_291]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355) ~[?:1.8.0_291]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_291]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_291]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_291]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_291]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_291]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at me.earth.headlessforge.launch.Main$Companion.main(Main.kt:116) [headlessforge-1.1.jar:?]
        at me.earth.headlessforge.launch.Main.main(Main.kt) [headlessforge-1.1.jar:?]
root@pingbypass:~/.minecraft/mods# java -version
java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)
root@pingbypass:~/.minecraft/mods#
```

**Comment by cheroso1337** [comment]
@3arthqu4ke

**Comment by cheroso1337** [comment]
nvm
