### ISSUE TITLE
crash on startup again

### ISSUE THREAD

**Issue by cherosin** [3arthqu4ke/HeadlessForge#6]
```
root@cherfofos:~/.minecraft/mods# java -jar headlessforge-1.1.jar 
No .minecraft path given, assuming we are .minecraft/mods...
Starting HeadlessForge with Arguments: []
Starting Launchwrapper...
[16:49:29] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[16:49:29] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraftforge.fml.common.launcher.FMLTweaker
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_291]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_291]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355) ~[?:1.8.0_291]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_291]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_291]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_291]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_291]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_291]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at me.earth.headlessforge.launch.Main$Companion.main(Main.kt:116) [headlessforge-1.1.jar:?]
        at me.earth.headlessforge.launch.Main.main(Main.kt) [headlessforge-1.1.jar:?]
root@cherfofos:~/.minecraft/mods# java -version
java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)
root@cherfofos:~/.minecraft/mods# 
```

**Comment by cheroso1337** [comment]
ooooohhhhhh i was using forge 2855 tyyyyy
