### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by VanVVA** [3arthqu4ke/HeadlessForge#8]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  HeadlessForge (headlessforge-1.1.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 6/23/21 12:53 PM
Description: Initializing game

java.lang.IllegalStateException: glGenLists returned an ID of 0 for a count of 1, GL error (-1): null
	at net.minecraft.client.renderer.GLAllocation.func_74526_a(SourceFile:27)
	at net.optifine.render.CloudRenderer.<init>(CloudRenderer.java:45)
	at net.minecraft.client.renderer.RenderGlobal.<init>(RenderGlobal.java:268)
	at me.earth.headlessforge.inject.replace.EmptyRenderGlobal.<init>(EmptyRenderGlobal.kt:24)
	at net.minecraft.client.Minecraft.lambda$renderGlobalHook$6(Minecraft.java:3448)
	at net.minecraft.client.Minecraft$$Lambda$82/609451568.get(Unknown Source)
	at me.earth.headlessforge.inject.Hooks.lambdaHook(Hooks.kt:35)
	at net.minecraft.client.Minecraft.redirect$renderGlobalHook$zzb000(Minecraft.java:3448)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:527)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.GLAllocation.func_74526_a(SourceFile:27)
	at net.optifine.render.CloudRenderer.<init>(CloudRenderer.java:45)
	at net.minecraft.client.renderer.RenderGlobal.<init>(RenderGlobal.java:268)
	at me.earth.headlessforge.inject.replace.EmptyRenderGlobal.<init>(EmptyRenderGlobal.kt:24)
	at net.minecraft.client.Minecraft.lambda$renderGlobalHook$6(Minecraft.java:3448)
	at net.minecraft.client.Minecraft$$Lambda$82/609451568.get(Unknown Source)
	at me.earth.headlessforge.inject.Hooks.lambdaHook(Hooks.kt:35)
	at net.minecraft.client.Minecraft.redirect$renderGlobalHook$zzb000(Minecraft.java:3448)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:527)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 844270456 bytes (805 MB) / 1308622848 bytes (1248 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_G5 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID        | Version      | Source                        | Signature                                |
	|:----- |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCH   | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| LCH   | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| LCH   | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge     | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |

	Loaded coremods (and transformers): 
HeadlessForge (headlessforge-1.1.jar)
  me.earth.headlessforge.asm.HeadlessForgeTransformer
	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL:  GL version , 
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: <unknown>
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: null
	OpenGlRenderer: null
	OpenGlVendor: null
	CpuCount: 2

**Comment by 3arthqu4ke** [comment]
Take Optifine out of your mods folder.

**Comment by VanVVA** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  HeadlessForge (headlessforge-1.1.jar)
  Core (pingbypass-1.0.0-release.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 6/25/21 9:54 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from PingBypass (pingbypass)
Caused by: java.net.BindException: Cannot assign requested address: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:437)
	at sun.nio.ch.Net.bind(Net.java:429)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:554)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1258)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:980)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:250)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:365)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 961509544 bytes (916 MB) / 1308622848 bytes (1248 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID         | Version      | Source                        | Signature                                |
	|:----- |:---------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHI  | minecraft  | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHI  | mcp        | 9.42         | minecraft.jar                 | None                                     |
	| LCHI  | FML        | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge      | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHE  | pingbypass | 1.0.0        | pingbypass-1.0.0-release.jar  | None                                     |

	Loaded coremods (and transformers): 
HeadlessForge (headlessforge-1.1.jar)
  me.earth.headlessforge.asm.HeadlessForgeTransformer
Core (pingbypass-1.0.0-release.jar)

**Comment by VanVVA** [comment]
nvm i got it fixied
